### ISSUE TITLE
$Score Variable missing, error in insert query

### ISSUE THREAD

**Issue by gotspatel** [palinkas-jo-reggelt/hMailServer_pURIBL#2]
Hi there

Line 421 ->> MySQLQuery "INSERT INTO $pURIBLDomTable (domain,strid,timestamp,adds,**hits**,shortcircuit) VALUES ('$MainDomain',MD5('$MainDomain'),NOW(),1,**0**,0)

-- Missing hits column and its value

Line 566 ->> Write-Output "score    PURIBL_$StrID  **$Score**" | Out-File $RuleFile -Append -Encoding ASCII

Where and how to get $Score variable from?

TIA

**Comment by palinkas-jo-reggelt** [comment]
Add to Spamassassin Variables at the top:
```
$Score                 = 5                 # Score for rules when creating custom pURIBL ruleset
```

For the other one, hits should be removed since we're looking at adds. During HAM inspection, if a URL is found, it should be treated as spam and knocked with a hit. But during SPAM inspection, we're looking for new URLs to add to the database. Duplicates are marked as "adds". So remove hits altogether from this query:
```
										MySQLQuery "INSERT INTO $pURIBLURITable (uri,strid,domain,timestamp,adds,active) VALUES ('$URI',MD5('$URI'),'$MainDomain',NOW(),1,1) ON DUPLICATE KEY UPDATE adds=(adds+1),timestamp=NOW();"
```

Thanks for pointing that out.

**Comment by gotspatel** [comment]
For the otherone agreed but hits column in both URI and DOM is NOT NULL hence it will require a 0 value in the query.

`27/06/2022 06:46 PM : ERROR : Exception calling "Fill" with "2" argument(s): "Field 'hits' doesn't have a default value"
`

**Comment by palinkas-jo-reggelt** [comment]
Just change default to 0. 😀

**Comment by gotspatel** [comment]
Already did that, it is just FYI that the query is missing the hits column and its default value 0. ;-)

precisely the $pURIBLDomTable  query
